# Site settings
title: Daniel's Programming Blog
email: da222kk@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
  Follow my journey as I explore the world of programming at LNU in Sweden.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  MassMonstarr
disqus_shortname: massmonstarr
# Build settings
markdown: kramdown
